text:
  # upper text
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  # lower text
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - upper text
  - lower text
overlay:
  # overlay a custom image at a specific position
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    # overlay size in terms of base image size
    scale: 0.25
